### Tutorial 8- Python Numpy Arrays 

### Numpy Tutorials 

Numpy is a general -purpose array-processing package. It provides a high-performance multidimensional
array object and tools for working  with these arrays.It is the fundamental package for scientific
computing with python.


### What is an array

An array is a data structure that store values of same data type. In Python, this is the main difference
between arrays and lists.While python list can contains values corresponding to different data types ,
arrays in python  can only contains values corresponding to same data type

In [1]:
### import the library
import numpy as np


In [5]:
lst=[1,2,3,4,5,6]
arr=np.array(lst)

In [6]:

type(arr)

numpy.ndarray

In [7]:
arr.shape

(6,)

In [11]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [13]:
arr1.shape

(3, 5)

In [14]:
#indexing

In [15]:
arr

array([1, 2, 3, 4, 5, 6])

In [16]:
arr[3]

4

In [17]:
#changing element

In [18]:
arr[2:4]

array([3, 4])

In [19]:
arr[-1]

6

In [20]:
arr[:-1]

array([1, 2, 3, 4, 5])

In [21]:
arr[::]

array([1, 2, 3, 4, 5, 6])

In [22]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [23]:
arr[::-2]

array([6, 4, 2])

In [25]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [26]:
arr1[:,0]

array([1, 2, 3])

In [27]:
arr1[2,:]

array([3, 4, 5, 6, 7])

In [29]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [30]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [32]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [34]:
arr1[:,0::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [35]:
##EDA
arr

array([1, 2, 3, 4, 5, 6])

In [36]:
arr[arr<2]

array([1])

In [37]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [39]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [42]:
# mechanism to create an array
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [43]:
arr * arr

array([ 1,  4,  9, 16, 25, 36])

In [44]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [45]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.random.randint(10,50,4)

array([45, 46, 10, 42])

In [50]:
np.random.randint(10,50,4).reshape(2,2)

array([[42, 17],
       [41, 35]])

In [52]:
np.random.random_sample((4,7))

array([[0.23647104, 0.20523643, 0.28190705, 0.24620219, 0.42737973,
        0.18126611, 0.41604379],
       [0.04739712, 0.18693827, 0.95939885, 0.16761039, 0.73248775,
        0.9180094 , 0.91053838],
       [0.42990807, 0.41289481, 0.63839252, 0.97706307, 0.20605737,
        0.40644871, 0.61107059],
       [0.26627037, 0.42186174, 0.99286262, 0.91762822, 0.25218179,
        0.4577479 , 0.18669364]])