### Tutorial 9- Python Pandas Tutorials-part 1

In  Part we are going to learn about
1.Pandas Dataframe
2.Pandas Series
3.Pandas Basic Operations

In [3]:
import pandas as pd
import numpy as np


In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
## Create DataFrame
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4",])

In [8]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
df.head() ## gives bydefault top 5 records

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
df.tail() ##gives last top 5 records

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [13]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [15]:
### indexing
# columname,rowindex[loc],rowindex columnindex number[.iloc]
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [16]:
df[['Column1','Column2','Column3']] #by using column name

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [17]:
df['Column2'] # by using column name

Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Column2, dtype: int32

In [18]:
type(df['Column2']) #single column or single row is called series

pandas.core.series.Series

In [20]:
type(df[['Column1','Column2','Column3']])# also collection of rows and columns is called data frame

pandas.core.frame.DataFrame

In [21]:
df.loc['Row3'] #by using rowindexp[loc]

Column1     8
Column2     9
Column3    10
Column4    11
Name: Row3, dtype: int32

In [22]:
type(df.loc['Row3'])

pandas.core.series.Series

In [24]:
df.loc[['Row3','Row5']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row5       16       17       18       19

In [26]:
type(df.loc[['Row3','Row5']])

pandas.core.frame.DataFrame

In [27]:
# rowindex columnindex number[.iloc]
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [28]:
# here i want 8 9 12 13
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [29]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [30]:
df.iloc[:,0::4]

Column1
Row1        0
Row2        4
Row3        8
Row4       12
Row5       16

In [31]:
# Select only Column1 and Column4 using iloc
df_selected = df.iloc[:, [0, 3]]

# Display the selected columns
print(df_selected)


      Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19


In [32]:
# convert dataframe into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [33]:
# Basic operatiom
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [36]:
df1=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],columns=["Column1","Column2","Column3",])

In [37]:
df1

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [39]:
df1.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [41]:
df1.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [43]:
df['Column3'].value_counts()

Column3
2     1
6     1
10    1
14    1
18    1
Name: count, dtype: int64

In [44]:
df['Column3'].unique()

array([ 2,  6, 10, 14, 18])

In [46]:
df[df['Column3']>2] #conditional

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19